name: Build on macos-15-intel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  JCPP_LOG_LEVEL: debug
  JCPP_LOG_CONSOLE: enable

jobs:
  build:
    runs-on: macos-15-intel

    steps:
    - uses: actions/checkout@v4

    - name: install libffi
      run: brew install libffi

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 8 --target install

    - name: Test
      working-directory: ${{github.workspace}}/build/test
      run: ctest -C Release --exclude-from-file ${{github.workspace}}/.github/workflows/ctestexclude-macos.txt -VV