name: Build on manylinux_2_28-x86_64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_28_x86_64

    steps:
    - run: git clone --recursive https://github.com/${{github.repository}} ${{github.workspace}}/src

    - uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 5

    - name: Package
      run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

    - name: Package source
      run: cpack --config ${{github.workspace}}/build/CPackSourceConfig.cmake

    - uses: actions/upload-artifact@v4
      with:
        name: java.base-17.35-source
        path: ${{github.workspace}}/java.base-17.35.tar.gz

    - uses: actions/upload-artifact@v4
      with:
        name: java.base-17.35-linux-x86_64
        path: ${{github.workspace}}/java.base-17.35-linux-x86_64.tar.gz

    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build -C Release --exclude-from-file ${{github.workspace}}/src/.github/workflows/ctestexclude-linux-manylinux_2_28-x86_64.txt -VV

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v5
      with:
        name: java.base-17.35-linux-x86_64

    - run: tar xzvf java.base-17.35-linux-x86_64.tar.gz
    - run: ./java.base-17.35-linux-x86_64/bin/java.base-test